config/routes.rb
Socialfeeds::Application.routes.draw do
  root to: "sessions#new"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy", :as => "logout"
  get "/create", to: "sessions#create", :as => "feeds"
  resources :groups
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Prototype', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li> <%= link_to "Log out", logout_path %></li>
          <li><%= link_to "Manage Groups", groups_path %></li>
        <% end %>
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Prototype" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Prototype" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "jquery.expander.min" %>
    <%= csrf_meta_tags %>
    <script>
    $(document).ready(function() {
        var opts = {collapseTimer: 4000};

        $.each(['beforeExpand', 'afterExpand', 'onCollapse'], function(i, callback) {
          opts[callback] = function(byUser) {
            var by, msg = '<div class="success">' + callback;

            if (callback == 'onCollapse') {
              msg += ' (' + (byUser ? 'user' : 'timer') + ')';
            }
            msg += '</div>';

            $(this).parent().parent().append(msg)
          }
        });
        
      $('article.expander').expander({
          slicePoint: 140,
          widow: 20,
          expandSpeed: 0,
          expandText: '<i class="glyphicon glyphicon-chevron-right"></i>',
          userCollapseText: '<i class="glyphicon glyphicon-chevron-up"></i>'
        });
    });
    </script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>